### ISSUE TITLE
Widevine CDM files should not be hosted by this repo

### ISSUE THREAD

**Issue by Zorig** [webcatalog/electron-widevinecdm#6]
Hi, @quanglam2807,
Do you know that Widevine CDM may not host for redistribution?? There is actual link for download directly from google you should use that instead hosting it in repo

**Comment by quanglam2807** [comment]
@Zorig Where can I find those links?

**Comment by Zorig** [comment]
I do not know, but you should contact widevine contributors or google support or hosting CDM is illegal. You might get yourself into trouble.

**Comment by quanglam2807** [comment]
@Zorig I'll have a look. Right now, I'm not storing the binaries in the repo but in the releases page so it's an easy fix if something goes wrong.

**Comment by quanglam2807** [comment]
tomasmcm/SpotiWeb#22 looks like the good starting point. But the files are outdated.

**Comment by Zorig** [comment]
@quanglam2807 indeed it is, if it helped maybe it will fix not only 64bit, 32 bit too right?

**Comment by Zorig** [comment]
there is still something i don't understand, that `widevinecdmadapter.plugin` for mac OS X and `widevinecdmadapter.dll` is not included. In order to work `widevinecdm.dll`
`widevinecdmadapter.dll` or `libwidevinecdm.dylib` `widevinecdmadapter.plugin` both should be included right?

**Comment by quanglam2807** [comment]
@Zorig You're correct. But I think the files on googlesource.com are just reference files. They are outdated. Google Chrome use `componentUpdater` to load Widevine from its server and Electron strips away this component. 

Brave Browser uses a modified version of Electron: https://github.com/brave/muon which still includes `componentUpdater`. So they simply call a function: https://github.com/brave/browser-laptop/blob/master/app/extensions.js#L545. 

It seems keeping the binaries in GitHub Releases is the most practical solution we have at the moment. The binaries are not included in the source code or the Electron app at all so if you use it in your app, I don't think it would be a deal. About this repo, Google may request me to take down the binaries but I don't think it would affect the source code. 

In longer-term, I think we will soon move to brave/muon instead of Electron because it allows us to both use Chrome extensions and Widevine.

**Comment by Zorig** [comment]
oh so that is. But what about 32bit plugins?

**Comment by quanglam2807** [comment]
@Zorig So right now, the repo relies on CIs to download the binaries automatically. These CIs use 64-bit Chrome so if we can find a way to have Chrome 32-bit on Windows and Chrome 32-bit on Linux, it would be possible 👍

**Comment by Zorig** [comment]
got it.
